- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ azure_rg }}"
    name: "{{ vnet_name }}"
    address_prefixes: "{{ virtual_net_cidr }}"

- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ azure_rg }}"
    name: "{{ vsubnet_name }}"
    address_prefix: "{{ virtual_subnet_cidr }}"
    virtual_network_name: "{{ vnet_name }}"

- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: "{{ azure_rg }}"
    allocation_method: Static
    name: webPublicIP
  register: output_ip_address

- name: Output public IP
  debug:
    msg: "The public IP is {{ output_ip_address.state.ip_address }}"

- name: Create Network Security Group
  azure_rm_securitygroup:
    resource_group: "{{ azure_rg }}"
    name: networkSecurityGroup
    rules:
      - name: 'allow_rdp'
        protocol: Tcp
        destination_port_range: 3389
        access: Allow
        priority: 1001
        direction: Inbound
      - name: 'allow_web_traffic'
        protocol: Tcp
        destination_port_range:
          - 80
          - 443
        access: Allow
        priority: 1002
        direction: Inbound
      - name: 'allow_powershell_remoting'
        protocol: Tcp
        destination_port_range: 
          - 5985
          - 5986
        access: Allow
        priority: 1003
        direction: Inbound

- name: Create a network interface
  azure_rm_networkinterface:
    name: "{{ physical_interface_name }}"
    resource_group: "{{ azure_rg }}"
    virtual_network: "{{ vnet_name }}"
    subnet_name: "{{ vsubnet_name }}"
    security_group: networkSecurityGroup
    ip_configurations:
      - name: default
        public_ip_address_name: webPublicIP
        primary: True