- name: Azure configuration
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: echo
    shell: |
      cat /root/.azure/credentials
    register: echo

  - debug: 
      var: echo.stdout_lines
  
  - name: Create an azure container registry
    azure_rm_containerregistry:
      name: autoapp
      location: eastus
      resource_group: myResourceGroupTest
      admin_user_enabled: true
      sku: Basic
      tags:
          Release: v1
          Environment: Production

  - name: Login to azure
    shell: az login --service-principal --username "{{lookup('env', 'client_id')}}" --password "{{lookup('env', 'secret')}}" --tenant "{{lookup('env', 'tenant')}}"
    register: ps

  - debug: 
      var: ps.stdout_lines

  #- name: Docker push to the registry
  #  shell: |
  #    az acr login --name autoapp
  #    docker pull mcr.microsoft.com/azuredocs/azure-vote-front:v1
  #    docker tag mcr.microsoft.com/azuredocs/azure-vote-front:v1 autoapp.azurecr.io/azure-vote-front:v1
  #    docker push autoapp.azurecr.io/azure-vote-front:v1

  - name: Create aks cluster
    shell: |
      az aks create --resource-group myResourceGroupTest --name myAutoApp --node-count 2 --generate-ssh-keys --attach-acr autoapp 2>/dev/null &  

  - name: Apply credentials with azure-cli to kubectl
    shell: |
      az aks install-cli
      az aks get-credentials --resource-group myResourceGroupTest --name myAutoApp

  - name: Deploy Kubernetes spec
    shell: |
      kubectl apply -f /home/kubeapplication.yml
    register: kube

  - debug: 
      var: kube.stdout_lines
