name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: make build-stable

  check:
    name: Syntax Check
    runs-on: ubuntu-latest
    container:
      image: maissacrement/ansibledind:b8c1df7-stable
      options: --entrypoint="/home/entrypoint.sh run" --privileged -u root
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: list repo
        run: ls && pwd

      - name: Run Ansible Syntax Check
        working-directory: ./ansible
        run: >
          ansible-playbook --syntax-check site.yml --extra-vars "ansible_role_include_tasks=true"

  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    container:
      image: maissacrement/ansibledind:b8c1df7-stable
      options: --entrypoint="/home/entrypoint.sh run" --privileged -u root
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Ansible Lint
        working-directory: ./ansible
        run: ansible-lint -vv
