name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main



jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: make build-stable

runs:
  image: maissacrement/ansibledind:b8c1df7-stable
  entrypoint: "/home/entrypoint.sh run"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: list repo
      run: ls && pwd

    - name: Run Ansible Syntax Check
      run: >
        ansible-playbook --syntax-check nodes-default-conf/site.yml
        -i nodes-default-conf/inventory/inventory.yml
        --extra-vars "ansible_role_include_tasks=true"

